apiVersion: batch/v1
kind: Job
metadata:
  name: apply-config
  namespace: es-config
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: es-config-app
spec:
  template:
    spec:
      containers:
        - name: apply-config
          image: fastapi-app:latest
          imagePullPolicy: Never
          command: ["python", "/app/hooks/post-sync.py", "complete"]
          env:
            - name: PYTHONPATH
              value: "/app"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: example-config
  backoffLimit: 3
