apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: es-config-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JulienDanh/argo.git
    targetRevision: HEAD
    path: es-config
  destination:
    server: https://kubernetes.default.svc
    namespace: es-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
