apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi-app

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: fastapi-app
  version: v1.0.0 