apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi-app

resources:
- namespace.yaml
- pre-sync-hook.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- post-sync-hook.yaml 
- configmap.yaml 