apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-hook
  namespace: fastapi-app
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app: fastapi-app
    version: v1.0.0
spec:
  template:
    spec:
      containers:
      - name: post-sync-hook
        image: fastapi-app:latest
        imagePullPolicy: Never
        command: ["python", "/app/hooks/post-sync.py", "complete"]
        env:
        - name: PYTHONPATH
          value: "/app"
      restartPolicy: Never
  backoffLimit: 3 